"""Physics Simulation Agent core contracts."""

from .schema import (
    Assumption,
    CFDExtension,
    PhysicsProblemSchema,
    Provenance,
    Quantity,
    ValidationIssue,
    ValidationResult,
)
from .adapters import (
    CapabilityResult,
    DomainPackMetadata,
    OpenFOAMAdapter,
    SolverSelection,
)
from .registry import SolverRegistry, create_default_registry
from .intake import (
    ClarificationQuestion,
    DomainClassification,
    InputArtifact,
    IntakeDraft,
    build_schema_draft,
    classify_physics_domain,
    plan_clarifications,
    screenshot_text_artifact,
    table_file_artifact,
    table_text_artifact,
    text_artifact,
)
from .openfoam_case import OpenFOAMCaseManifest, choose_openfoam_solver, generate_openfoam_case
from .execution import (
    CommandResult,
    Diagnosis,
    EnvironmentCapability,
    ExecutionSummary,
    StageResult,
    detect_environment,
    diagnose_failure,
    execute_openfoam_case,
    parse_check_mesh_log,
    parse_solver_log,
    run_command,
)
from .delivery import (
    SanityCheck,
    ValidationEvidence,
    build_delivery_package,
    build_validation_evidence,
    extract_openfoam_metrics,
    generate_report,
    select_report_languages,
)
from .readiness import (
    MockWorkflowResult,
    ReadinessItem,
    ReleaseReadinessReport,
    check_fixture_structure,
    check_non_mvp_draft_only,
    check_test_surface,
    resolve_project_root,
    run_conditional_real_smoke,
    run_mock_full_workflow,
    run_release_readiness,
)
from .workspace import (
    DEFAULT_WORKFLOW,
    WORKFLOW_STAGES,
    WORKSPACE_DIRS,
    ArtifactRecord,
    CheckpointDecision,
    PlatformWorkspace,
    TaskState,
    WorkflowStep,
)
from .validation import validate_schema

__all__ = [
    "Assumption",
    "ArtifactRecord",
    "CapabilityResult",
    "CFDExtension",
    "CheckpointDecision",
    "ClarificationQuestion",
    "CommandResult",
    "DomainClassification",
    "DomainPackMetadata",
    "Diagnosis",
    "EnvironmentCapability",
    "ExecutionSummary",
    "InputArtifact",
    "IntakeDraft",
    "OpenFOAMAdapter",
    "OpenFOAMCaseManifest",
    "PhysicsProblemSchema",
    "Provenance",
    "Quantity",
    "MockWorkflowResult",
    "ReadinessItem",
    "ReleaseReadinessReport",
    "PlatformWorkspace",
    "SanityCheck",
    "SolverRegistry",
    "SolverSelection",
    "StageResult",
    "TaskState",
    "ValidationIssue",
    "ValidationEvidence",
    "ValidationResult",
    "WorkflowStep",
    "DEFAULT_WORKFLOW",
    "WORKFLOW_STAGES",
    "WORKSPACE_DIRS",
    "build_schema_draft",
    "build_delivery_package",
    "build_validation_evidence",
    "classify_physics_domain",
    "check_fixture_structure",
    "check_non_mvp_draft_only",
    "check_test_surface",
    "create_default_registry",
    "choose_openfoam_solver",
    "detect_environment",
    "diagnose_failure",
    "execute_openfoam_case",
    "extract_openfoam_metrics",
    "generate_openfoam_case",
    "generate_report",
    "parse_check_mesh_log",
    "parse_solver_log",
    "plan_clarifications",
    "resolve_project_root",
    "run_command",
    "run_conditional_real_smoke",
    "run_mock_full_workflow",
    "run_release_readiness",
    "select_report_languages",
    "screenshot_text_artifact",
    "table_file_artifact",
    "table_text_artifact",
    "text_artifact",
    "validate_schema",
]
